# File: environment.yml
# File Created: Monday, 22nd April 2019
# Author: Steven Atkinson (212726320@ge.com)

name: pirate
channels:
  - pytorch  # pytorch
dependencies:
  - black
  - h5py
  - jupyter
  - matplotlib
  - numpy
  - pandas
  - pip
  - python>=3.7
  - pytorch>=1.3
  - pytest
  - scikit-learn
  - seaborn
  - sympy
  - xlrd>=1
  - pip:
    - deap
    - gptorch<0.3
    - pre-commit
    - pyro-ppl>=1
    - pyglet
    - tqdm
